name: CI/CD for simple-http-checker

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Display Python version and location
        run: | 
          python --version      
          which python
      - name: Install dependencies    
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: Linting and Formatting Check
        run: |
          ruff check .
          black --check . 
      - name: Static Type Checking
        run: |
          mypy src/      
      - name: Security Check
        run: |
          bandit -c pyproject.toml -r .
   